#!/bin/bash
#
# Description : Mugen Installer
# Author      : Supreme Team
# Version     : 1.0
#
clear

setup_start() {
echo "$(tput setaf 6)
  _   _   _     _   _   _   _   _     _   _   _   _   _   _   _   _   _
 / \ / \ / \   / \ / \ / \ / \ / \   / \ / \ / \ / \ / \ / \ / \ / \ / \ 
( T | H | E ) ( M | U | G | E | N ) ( I | N | S | T | A | L | L | E | R )
 \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/ \_/
  _   _     _   _   _     _   _   _   _   _   _   _     _   _   _   _  
 / \ / \   / \ / \ / \   / \ / \ / \ / \ / \ / \ / \   / \ / \ / \ / \ 
( B | Y ) ( T | H | E ) ( S | U | P | R | E | M | E ) ( T | E | A | M )
 \_/ \_/   \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/ \_/ \_/   \_/ \_/ \_/ \_/ 
  _   _   _     _   _   _   _   _     _   _   _   _   _   _  
 / \ / \ / \   / \ / \ / \ / \ / \   / \ / \ / \ / \ / \ / \ 
( A | N | D ) ( R | E | T | R | O ) ( D | E | V | I | L | S )
 \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/   \_/ \_/ \_/ \_/ \_/ \_/ 
$(tput sgr0)"
sleep 5
update_check
}

function update_check() { 
echo -e "$(tput setaf 2)
***Please note this install could take up to 30 mins*** 
$(tput sgr0)"
sleep 10

echo -e "$(tput setaf 2)
Lets first make sure your up to date!
$(tput sgr0)"
sleep 3

#Basic Update
sudo apt -y clean
sleep 2
sudo apt-get -y update --allow-releaseinfo-change
sleep 2
#Double check update on clean RetroPie.
sudo apt -y update
sleep 2
sudo apt -y upgrade
sleep 2

echo -e "$(tput setaf 2)
Done!
$(tput sgr0)"
sleep 3
clear

#Installer Steps
install_retropie_scriptmodules
install_mugen_new
setup_controller
}

install_retropie_scriptmodules() {
echo -e "$(tput setaf 2)
Lets Now Install Needed RetroPie Scriptmodules.
$(tput sgr0)"
sleep 3

cd $HOME/RetroPie-Setup
git fetch --quiet
git reset --hard HEAD --quiet
git clean -d -f --quiet
git merge '@{u}' --quiet

git clone --branch emulator https://github.com/GeorgeMcMullen/rp-box86wine /home/pi/RetroPie-Setup/ext/rp-box86wineemu/ --quiet

cd $HOME/RetroPie-Setup
sudo ./retropie_packages.sh raspbiantools lxde
sudo ./retropie_packages.sh mesa
sudo ./retropie_packages.sh box86
sudo ./retropie_packages.sh wine
sudo ./retropie_packages.sh raspbiantools package_cleanup


    if [[ ! -d /home/pi/RetroPie/roms/wine/wine-apps ]]; then
        mkdir /home/pi/RetroPie/roms/wine/wine-apps
    fi

sudo mv /home/pi/RetroPie/roms/wine/wine* /home/pi/RetroPie/roms/wine/wine-apps

#Add retro devils Desktop file
curl -s https://raw.githubusercontent.com/Retro-Devils/Mugen-Pi-4/main/Wine%20Desktop.sh -o /home/pi/RetroPie/roms/wine/Wine\ Desktop.sh
sudo chmod +x /home/pi/RetroPie/roms/wine/Wine\ Desktop.sh
}


install_mugen_new() {
    if [[ ! -d /home/pi/RetroPie/roms/wine/games ]]; then
        mkdir /home/pi/RetroPie/roms/wine/games
    fi

cd /home/pi/RetroPie/roms/wine/games/
wget -q http://network.mugenguild.com/justnopoint/mugen100.zip
unzip -o mugen100.zip
sudo rm mugen100.zip
sudo mv mugen Mugen
cd
sudo chmod 755 -R /home/pi/RetroPie/roms/wine/games/Mugen
sudo chown pi:pi -R /home/pi/RetroPie/roms/wine/games/Mugen
cat <<\EOF85222 > "/home/pi/RetroPie/roms/wine/games/mugen.sh"
#!/bin/bash

cd "/home/pi/RetroPie/roms/wine/games/Mugen"

qjoypad "mugen" &

WINEDEBUG=-all LD_LIBRARY_PATH="/opt/retropie/supplementary/mesa/lib/" setarch linux32 -L /opt/retropie/emulators/wine/bin/wine '/home/pi/RetroPie/roms/wine/games/Mugen/mugen.exe'
EOF85222

sudo chmod +x /home/pi/RetroPie/roms/wine/games/mugen.sh

curl -s https://raw.githubusercontent.com/Retro-Devils/Mugen-Pi-4/main/Mugen.cfg -o /home/pi/RetroPie/roms/wine/games/Mugen/data/mugen.cfg
sudo chmod +x /home/pi/RetroPie/roms/wine/games/Mugen/data/mugen.cfg

echo -e "$(tput setaf 2)
Done!
$(tput sgr0)"
clear
sleep 3

sudo cat <<\EOF2323 > "/home/pi/Xwrapper.config"
# Xwrapper.config (Debian X Window System server wrapper configuration file)
#
# This file was generated by the post-installation script of the
# xserver-xorg-legacy package using values from the debconf database.
#
# See the Xwrapper.config(5) manual page for more information.
#
# This file is automatically updated on upgrades of the xserver-xorg-legacy
# package *only* if it has not been modified since the last upgrade of that
# package.
#
# If you have edited this file but would like it to be automatically updated
# again, run the following command as root:
#   dpkg-reconfigure xserver-xorg-legacy
allowed_users=anybody
needs_root_rights=yes
EOF2323

sudo chmod +x /home/pi/Xwrapper.config
sudo mv /home/pi/Xwrapper.config /etc/X11/Xwrapper.config
}

setup_controller() {
echo -e "$(tput setaf 2)
Now Installing Qjoypad for Mugen controller setup.
$(tput sgr0)"

sudo dpkg --configure -a
sudo apt-get install qjoypad

    if [[ ! -d /home/pi/.qjoypad3 ]]; then
        mkdir /home/pi/.qjoypad3
    fi

#Add PS3 Qjoypad Layouts

    if [[ -f /home/pi/.qjoypad3/*.lyt ]]; then
        sudo rm /home/pi/.qjoypad3/*.lyt
    fi

wget -q https://www.mediafire.com/file/wo2odt49p3y1jjr/Baldurs_Gate.lyt -P /home/pi/.qjoypad3/
wget -q https://www.mediafire.com/file/zs16mbv1k4uhkgh/mugen.lyt -P /home/pi/.qjoypad3/
wget -q https://www.mediafire.com/file/7dq9302v4257gjl/Spooky_Castle.lyt -P /home/pi/.qjoypad3/

sudo chmod +x /home/pi/.qjoypad3/*

echo -e "$(tput setaf 2)
Done installing qjoypad.

To set up Qjoypad please visit the pixel desktop to map your controler input and then save the layout as "mugen". 
Once this "mugen" layout is saved boot back into ES and copy your Qjoypad inputs for your mugen games.

For your Convince some have been made with the PS3 controller.
$(tput sgr0)"
sleep 10

echo -e "$(tput setaf 2)
Now Rebooting to save changes, please wait...
$(tput sgr0)"
sleep 3
clear

sudo reboot
}

setup_start
